USB_VID = 0x239A
USB_PID = 0x8023
USB_PRODUCT = "SugarCookie"
USB_MANUFACTURER = "Brian Dahlem"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 0
EXTERNAL_FLASH_DEVICE_COUNT = 0
LONGINT_IMPL = MPZ

CIRCUITPY_BITBANGIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CSLAVE = 0

CFLAGS_INLINE_LIMIT = 60
SUPEROPT_GC = 0
