USB_VID = 0x16D0
USB_PID = 0x0F3D
USB_PRODUCT = "SugarCookie"
USB_MANUFACTURER = "Brian Dahlem"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_SMALL_BUILD = 1

SUPEROPT_GC = 0
