USB_VID = 0x16D0
USB_PID = 0x0F3D
USB_PRODUCT = "SugarCookie"
USB_MANUFACTURER = "Brian Dahlem"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

# external flash
#SPI_FLASH_FILESYSTEM = 1
#EXTERNAL_FLASH_DEVICE_COUNT = 1
#EXTERNAL_FLASH_DEVICES = GD25Q32C
#LONGINT_IMPL = MPZ

# internal flash
INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_SMALL_BUILD = 1

CIRCUITPY_BITBANGIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CSLAVE = 0

#CFLAGS_INLINE_LIMIT = 60
SUPEROPT_GC = 0
